version: '3.8'

services:
  db:
    image: postgres:13
    container_name: flask_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "flask_db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - app-network

  flask:
    build: .
    entrypoint: /app/init_db.sh
    command: ["poetry", "run", "gunicorn", "-b", "0.0.0.0:5000", "app:app"]
    ports:
      - "5000:5000"
    container_name: flask_app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: ${DB_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pg-data:
    driver: local

networks:
  app-network:
    driver: bridge






